import {readdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
async function walk(path){return(await Promise.all((await readdir(path,{withFileTypes:true})).map(async e=>e.isDirectory()?walk(`${path}/${e.name}`):`${path}/${e.name}`))).flat();}
const sources=[...await walk('public'),...await walk('core')].filter(f=>!f.endsWith('/sw.js')).sort();
const hash=createHash('sha256');
for(const file of sources)hash.update(file).update(await readFile(file));
const vendor=await readFile('node_modules/fflate/esm/browser.js');hash.update('/vendor/fflate.js').update(vendor);
const digest=hash.digest('hex').slice(0,16);
const files=[...sources.map(f=>f.startsWith('public/')?f.slice(6):'/'+f),'/vendor/fflate.js'];
const code=`// Generated by npm run build:sw. Never cache authenticated API responses.
const CACHE='vocalearn-0.1.0-${digest}';
const ASSETS=${JSON.stringify(files)};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('vocalearn-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  const url=new URL(event.request.url);
  if(event.request.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/'))return;
  if(event.request.mode==='navigate')event.respondWith(fetch(event.request).catch(()=>caches.match('/index.html')));
  else event.respondWith(caches.match(event.request).then(hit=>hit||fetch(event.request)));
});
`;
await writeFile('public/sw.js',code);
